# Generated by Django 4.1 on 2022-09-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tilte',
            new_name='title',
        ),
    ]
